export enum BookingStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  CONFIRMED = 'CONFIRMED',
  REJECTED = 'REJECTED',
  CANCELLED_BY_RENTER = 'CANCELLED_BY_RENTER',
  CANCELLED_BY_HOST = 'CANCELLED_BY_HOST',
}

export enum ProcessBookingStatus {
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}